### ISSUE TITLE
How can I get only text effect 🥺

### ISSUE THREAD

**Issue by SomnathDas** [CodyJasonBennett/portfolio#25]
Bro! This portfolio is sick ✨✨✨🍻🌞 
I loved that Japanese -> English text transitioning.
Can you help me, I only want to take that out of your project and use it. 🍻

**Comment by CodyJasonBennett** [comment]
It's a bit out of date but all of the components in my [components Storybook](https://storybook.codyb.co) are mapped to `src/components`.

Feel free to [contact me](https://codyb.co/contact) if you have any further questions.

**Comment by SomnathDas** [comment]
Ah 🍻
@CodyJasonBennett  Thanks pal 🌞
And again, it's an amazing project ✨
